### ISSUE TITLE
S Schubert Edit ReadMe file

### ISSUE THREAD

**Issue by ChanaMar2** [elishevarom/employee-accounts#14]

**Comment by elishevarom** [comment]
Same for this one. You will each be editing the README differently and you don't want to overlap and create conflicts. Create a separate task for each of you specifying how to edit the README.

**Comment by elishevarom** [comment]
@etamiller If you are adding a .gitignore file then no need to also edit the README

**Comment by SerachS** [comment]
I dont think that we need add a .dotgitignore because when we created the react app it automatically created one

**Comment by etamiller** [comment]
Got it. Ok
